# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: vuetify-unsplash-ci-cd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

      - name: Upload test report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
          flags: unittests
          fail_ci_if_error: true

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_VUE_APP_UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          file_name: .env.production

      - name: Generate static demo app
        run: npm run build-demo

      - name: Deploy to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-lib:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git Part 1
        run: git config user.email "mailines.service@gmail.com"

      - name: Configure Git Part 2
        run: git config user.name "Mailines"

      - name: Build library
        run: npm run build-bundle

      - name: Increment version number
        run: npm version patch

      - name: Publish library to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
